<a href="https://colab.research.google.com/github/vishwanaik15/Matrix_Factorization/blob/main/Assignmnet1_1001871311.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name: Vishwa Chetankumar Naik**<br>
**UTA ID: 1001871311**

**Programming Assignment 1**<br>
AIM: **Matrix Factorization Using Gradient Descent<br>**

There are many algorithms used for recomendation system but for this assignment I have learnt and used the matrix factorization.

In [247]:
import numpy
import numpy as np
import pandas as pd
import progressbar as pb

In [248]:
# Import Input file 1
input_file1  = open("input1.csv")
input_file1 = np.loadtxt(input_file1, delimiter=",")

In [249]:
print(input_file1)

[[6. 0. 3. 7. 2. 5. 4. 2. 4. 3. 0. 5. 0. 6. 0. 9. 2. 5. 4. 6. 1. 6. 4. 0.
  0. 3. 4. 1. 9. 1. 8. 0. 9. 1. 6. 4. 8. 6. 0. 0. 3. 9. 1.]
 [2. 0. 0. 8. 7. 3. 1. 2. 2. 0. 9. 6. 2. 7. 6. 6. 4. 7. 7. 7. 1. 6. 7. 5.
  4. 0. 5. 3. 3. 1. 7. 1. 1. 8. 7. 3. 5. 2. 4. 6. 6. 8. 1.]
 [0. 4. 0. 6. 8. 5. 4. 6. 0. 7. 4. 7. 1. 4. 3. 6. 2. 1. 1. 9. 7. 7. 6. 4.
  5. 7. 1. 9. 6. 2. 8. 3. 0. 3. 0. 2. 5. 9. 3. 1. 8. 8. 4.]
 [8. 8. 2. 5. 6. 9. 2. 3. 9. 9. 5. 3. 7. 3. 1. 8. 5. 6. 9. 2. 7. 9. 0. 4.
  1. 3. 3. 3. 2. 7. 2. 1. 6. 2. 9. 3. 5. 4. 6. 2. 7. 3. 4.]
 [8. 8. 9. 6. 6. 1. 2. 9. 8. 3. 8. 9. 7. 7. 1. 4. 3. 1. 1. 2. 5. 7. 5. 5.
  4. 4. 8. 5. 9. 7. 5. 1. 5. 4. 3. 0. 1. 4. 9. 5. 3. 9. 6.]
 [3. 5. 7. 8. 4. 5. 1. 0. 9. 6. 3. 6. 6. 7. 4. 5. 5. 5. 2. 3. 4. 0. 0. 8.
  4. 2. 1. 8. 1. 8. 7. 1. 2. 3. 5. 0. 5. 7. 2. 4. 7. 9. 2.]
 [4. 1. 7. 7. 2. 3. 1. 8. 4. 1. 6. 1. 8. 5. 4. 9. 3. 9. 9. 4. 7. 4. 0. 9.
  0. 0. 9. 4. 4. 8. 1. 2. 7. 0. 4. 3. 0. 3. 2. 6. 6. 2. 0.]
 [5. 9. 3. 5. 7. 0. 5. 4. 1. 7. 5. 6. 5. 8. 6. 9. 6. 0. 2. 2. 

In [250]:
print("Length of input: ",input_file1.shape)

Length of input:  (16, 43)


In [251]:
#Import input file 2
input_file2  = open("input2.csv")
input_file2 = np.loadtxt(input_file2, delimiter=",")

In [252]:
print(input_file2)

[[8. 0. 0. ... 2. 0. 0.]
 [6. 2. 0. ... 0. 2. 8.]
 [5. 4. 2. ... 1. 2. 9.]
 ...
 [4. 5. 4. ... 1. 1. 4.]
 [7. 4. 4. ... 3. 1. 5.]
 [0. 7. 4. ... 4. 7. 5.]]


In [253]:
print("Length of input: ",input_file2.shape)

Length of input:  (167, 43)


Factorization function

In [256]:
def matrix_factorization_gradient(X, A, B, Y, iterations=1000, alpha=0.0002, beta=0.02):
    B = B.T #taking the transpose of B it is multipliable by A.
    for iteration in pb.progressbar(range(iterations)): #progressbar to track the running time of for loops
        for i in range(len(X)):
            for j in range(len(X[i])):
                if X[i][j] > 0:
                    eij = X[i][j] - numpy.dot(A[i,:],B[:,j])
                    for y in range(Y):
                        A[i][y] = A[i][y] + alpha * (2 * eij * B[y][j] - beta * A[i][y])
                        B[y][j] = B[y][j] + alpha * (2 * eij * A[i][y] - beta * B[y][j])
        eR = numpy.dot(A,B)
        e = 0
        for i in range(len(X)):
            for j in range(len(X[i])):
                if X[i][j] > 0:
                    e = e + pow(X[i][j] - numpy.dot(A[i,:],B[:,j]), 2)
                    for y in range(Y):
                        e = e + (beta/2) * (pow(A[i][y],2) + pow(B[y][j],2))
        if e < 0.001:
            break
    return A, B.T

In [257]:
X = np.array(input_file1)
N = len(X)
M = len(X[0])
Y = 2

A = np.random.rand(N,Y)
B = np.random.rand(M,Y)

nA, nB = matrix_factorization(X, A, B, Y)
nX = numpy.dot(nA, nB.T)

100% (1000 of 1000) |####################| Elapsed Time: 0:00:17 Time:  0:00:17


In [258]:
pd.DataFrame(nX).to_csv('output1.csv')

In [259]:
nX # output for input file 1

array([[ 4.92706887,  4.58406237,  4.00444241,  5.41064739,  4.77614143,
         4.60966039,  3.71065162,  5.20857862,  4.89020793,  3.76528824,
         4.93084602,  5.56590878,  5.14351603,  5.03519118,  3.7679131 ,
         6.07162916,  3.49939705,  4.17610701,  4.43743932,  4.23469286,
         4.44245323,  5.36086195,  4.3560012 ,  4.69592066,  3.54728835,
         4.92893287,  4.47735876,  5.09006288,  4.39580219,  3.966184  ,
         4.41223275,  1.9994114 ,  5.01015394,  3.89673375,  4.90911481,
         4.06564539,  4.26312406,  5.5882655 ,  3.69300103,  3.76635525,
         5.4285751 ,  5.69789988,  4.27492054],
       [ 5.01614872,  4.5549454 ,  4.42609574,  5.14230243,  4.7909884 ,
         4.64331199,  3.97465211,  4.86723104,  4.71172051,  3.58543659,
         5.27365748,  5.72721514,  5.6103049 ,  4.8766985 ,  4.03350386,
         5.51361714,  3.26355129,  4.15901601,  4.73470877,  4.21831484,
         4.64330585,  4.47379639,  4.95141491,  4.40463458,  3.36542206,
   

In [260]:
X = np.array(input_file2)
N = len(X)
M = len(X[0])
Y = 2

A = np.random.rand(N,Y)
B = np.random.rand(M,Y)

nA, nB = matrix_factorization(X, A, B, Y)
nX = numpy.dot(nA, nB.T)

100% (1000 of 1000) |####################| Elapsed Time: 0:03:10 Time:  0:03:10


In [261]:
pd.DataFrame(nX).to_csv('output2.csv')

In [262]:
nX #output for input file 2

array([[5.09435514, 4.95025392, 4.69616161, ..., 4.96371076, 4.99352718,
        5.47697234],
       [4.48461009, 4.28532204, 4.1009331 , ..., 4.68356311, 4.70033727,
        5.59089753],
       [4.91358145, 4.62480289, 4.46097893, ..., 5.43682836, 5.44599596,
        6.87383997],
       ...,
       [4.76786662, 4.69469696, 4.42342269, ..., 4.37817747, 4.41415212,
        4.47056593],
       [4.3891454 , 4.24450515, 4.03669958, ..., 4.36538486, 4.38839436,
        4.9364283 ],
       [5.81116304, 5.78003702, 5.41791215, ..., 5.08457049, 5.13600986,
        4.83209801]])

**References:<br>**
<li>
https://towardsdatascience.com/recommendation-system-matrix-factorization-d61978660b4b
