<a href="https://colab.research.google.com/github/vishwanaik15/Matrix_Factorization/blob/main/Assignmnet1_1001871311.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name: Vishwa Chetankumar Naik**
**UTA ID: 1001871311**

**Programming Assignment 1**<br>
AIM: **Matrix Factorization Using Gradient Descent<br>**

There are many algorithms used for recomendation system but for this assignment I have learnt and used the matrix factorization.

In [232]:
import numpy
import numpy as np
import pandas as pd
import progressbar as pb

In [233]:
# Import Input file 1
input_file1  = open("input1.csv")
input_file1 = np.loadtxt(input_file1, delimiter=",")

In [234]:
print(input_file1)

[[6. 0. 3. 7. 2. 5. 4. 2. 4. 3. 0. 5. 0. 6. 0. 9. 2. 5. 4. 6. 1. 6. 4. 0.
  0. 3. 4. 1. 9. 1. 8. 0. 9. 1. 6. 4. 8. 6. 0. 0. 3. 9. 1.]
 [2. 0. 0. 8. 7. 3. 1. 2. 2. 0. 9. 6. 2. 7. 6. 6. 4. 7. 7. 7. 1. 6. 7. 5.
  4. 0. 5. 3. 3. 1. 7. 1. 1. 8. 7. 3. 5. 2. 4. 6. 6. 8. 1.]
 [0. 4. 0. 6. 8. 5. 4. 6. 0. 7. 4. 7. 1. 4. 3. 6. 2. 1. 1. 9. 7. 7. 6. 4.
  5. 7. 1. 9. 6. 2. 8. 3. 0. 3. 0. 2. 5. 9. 3. 1. 8. 8. 4.]
 [8. 8. 2. 5. 6. 9. 2. 3. 9. 9. 5. 3. 7. 3. 1. 8. 5. 6. 9. 2. 7. 9. 0. 4.
  1. 3. 3. 3. 2. 7. 2. 1. 6. 2. 9. 3. 5. 4. 6. 2. 7. 3. 4.]
 [8. 8. 9. 6. 6. 1. 2. 9. 8. 3. 8. 9. 7. 7. 1. 4. 3. 1. 1. 2. 5. 7. 5. 5.
  4. 4. 8. 5. 9. 7. 5. 1. 5. 4. 3. 0. 1. 4. 9. 5. 3. 9. 6.]
 [3. 5. 7. 8. 4. 5. 1. 0. 9. 6. 3. 6. 6. 7. 4. 5. 5. 5. 2. 3. 4. 0. 0. 8.
  4. 2. 1. 8. 1. 8. 7. 1. 2. 3. 5. 0. 5. 7. 2. 4. 7. 9. 2.]
 [4. 1. 7. 7. 2. 3. 1. 8. 4. 1. 6. 1. 8. 5. 4. 9. 3. 9. 9. 4. 7. 4. 0. 9.
  0. 0. 9. 4. 4. 8. 1. 2. 7. 0. 4. 3. 0. 3. 2. 6. 6. 2. 0.]
 [5. 9. 3. 5. 7. 0. 5. 4. 1. 7. 5. 6. 5. 8. 6. 9. 6. 0. 2. 2. 

In [235]:
print("Length of input: ",input_file1.shape)

Length of input:  (16, 43)


In [236]:
#Import input file 2
input_file2  = open("input2.csv")
input_file2 = np.loadtxt(input_file2, delimiter=",")

In [237]:
print(input_file2)

[[8. 0. 0. ... 2. 0. 0.]
 [6. 2. 0. ... 0. 2. 8.]
 [5. 4. 2. ... 1. 2. 9.]
 ...
 [4. 5. 4. ... 1. 1. 4.]
 [7. 4. 4. ... 3. 1. 5.]
 [0. 7. 4. ... 4. 7. 5.]]


In [238]:
print("Length of input: ",input_file2.shape)

Length of input:  (167, 43)


Factorization function

In [239]:
def matrix_factorization_gradient(X, A, B, Y, iterations=5000, alpha=0.0002, beta=0.02):
    B = B.T #taking the transpose of B it is multipliable by A.
    for step in pb.progressbar(range(steps)): #progressbar to track the running time of for loops
        for i in range(len(X)):
            for j in range(len(X[i])):
                if X[i][j] > 0:
                    eij = X[i][j] - numpy.dot(A[i,:],B[:,j])
                    for y in range(Y):
                        A[i][y] = A[i][y] + alpha * (2 * eij * B[y][j] - beta * A[i][y])
                        B[y][j] = B[y][j] + alpha * (2 * eij * A[i][y] - beta * B[y][j])
        eR = numpy.dot(A,B)
        e = 0
        for i in range(len(X)):
            for j in range(len(X[i])):
                if X[i][j] > 0:
                    e = e + pow(X[i][j] - numpy.dot(A[i,:],B[:,j]), 2)
                    for y in range(Y):
                        e = e + (beta/2) * (pow(A[i][y],2) + pow(B[y][j],2))
        if e < 0.001:
            break
    return A, B.T

In [240]:
X = np.array(input_file1)
N = len(X)
M = len(X[0])
Y = 2

A = np.random.rand(N,Y)
B = np.random.rand(M,Y)

nA, nB = matrix_factorization(X, A, B, Y)
nX = numpy.dot(nA, nB.T)

100% (1000 of 1000) |####################| Elapsed Time: 0:00:18 Time:  0:00:18


In [241]:
pd.DataFrame(nX).to_csv('output1.csv')

In [242]:
nX # output for input file 1

array([[ 4.99486438,  4.55582187,  4.27076655,  5.28431218,  4.78184455,
         4.66395709,  3.88934127,  4.96989069,  4.78564617,  3.63240958,
         5.27535272,  5.67128307,  5.48591128,  4.9221829 ,  3.9333038 ,
         5.8433961 ,  3.32908634,  4.16486054,  4.65390691,  4.22113859,
         4.57614985,  4.54897383,  4.94453971,  4.54058193,  3.36559279,
         5.1410059 ,  4.94847293,  5.12533496,  4.71704518,  3.73141364,
         4.68035195,  2.22049005,  4.9140774 ,  4.12744092,  4.75575164,
         4.21219213,  4.29293822,  5.45621677,  3.68822986,  4.15974056,
         5.27725946,  5.62832586,  3.97545163],
       [ 5.04049085,  4.67496779,  4.95313498,  5.05219184,  4.71408955,
         4.84802871,  3.86239213,  4.3424229 ,  4.69240154,  3.45676134,
         5.95052871,  5.57439811,  6.14656042,  4.75293326,  4.34257636,
         5.75473759,  2.94519754,  4.35654582,  5.31441227,  3.91620154,
         4.57436855,  3.50023661,  5.39454848,  4.17224874,  2.98053215,
   

In [243]:
X = np.array(input_file2)
N = len(X)
M = len(X[0])
Y = 2

A = np.random.rand(N,Y)
B = np.random.rand(M,Y)

nA, nB = matrix_factorization(X, A, B, Y)
nX = numpy.dot(nA, nB.T)

100% (1000 of 1000) |####################| Elapsed Time: 0:03:07 Time:  0:03:07


In [244]:
pd.DataFrame(nX).to_csv('output2.csv')

In [245]:
nX #output for input file 2

array([[5.13504865, 5.04028732, 4.75409822, ..., 4.90092173, 4.94061314,
        5.24173961],
       [4.60341089, 4.56929313, 4.20131129, ..., 4.62838032, 4.63817579,
        5.0218407 ],
       [5.21940658, 5.19211696, 4.7499205 , ..., 5.30035747, 5.30568395,
        5.76617585],
       ...,
       [4.70811301, 4.59005377, 4.39599575, ..., 4.34941059, 4.40161731,
        4.60796496],
       [4.45648272, 4.38948038, 4.10771127, ..., 4.3236913 , 4.35040833,
        4.645828  ],
       [5.6324467 , 5.43835445, 5.32205152, ..., 4.95912262, 5.04839129,
        5.17701327]])

**References:<br>**
<li>
https://towardsdatascience.com/recommendation-system-matrix-factorization-d61978660b4b
